#ifndef _DRIVER
#define _DRIVER
#include "lexerDef.h"
#include "lexer.h"
#include "grammar_Init.h" 
#include "grammar_InitDef.h"
#include "parser.h"
#include "parserDef.h"
#include "astGenerator.h"
#include "symbolTable.h"
#include "typeChecker.h"
#include <stdlib.h>
#include <time.h>

int main(int argc, char *argv[])
{	
	int input, flag=1;
	struct TOKEN_INFO token_info;
	struct ParseTreeNode *root=parseInputSourceCode(argv[1]);;
	struct ASTNode *AST_root=createAST(root);
	int parseNodes=0,astNodes=0;
	countParseNodes(root,&parseNodes);
	countASTNodes(AST_root,&astNodes);				    
	int parseMem=parseNodes*sizeof(struct ParseTreeNode);
	int astMem=astNodes*sizeof(struct ASTNode);
	SymbolTable *mainTable;
	clock_t start_time, end_time;
	double total_CPU_time, total_CPU_time_in_seconds;
	while(flag){
		printf("Choose option: ");
		scanf("%d",&input);
		switch(input)
		{
			case 0:
				//Option to exit the program
				flag=0;
				break;
			case 1:
				//Print tokens as generated by lexer
				initLexer(argv[1]);
				initGrammar("grammar.txt");
				while(1)
				{	
					token_info=getNextToken();
					if(token_info.token==EPS)	continue;
					printf("\t%-5d %-25s%s\n",token_info.lineno,token_info.lexeme,mapping[token_info.token].str);
					if(token_info.token==FEOF)	break;
				}
				break;
			case 2:
				//Verify syntactic correctness and print parse tree
				printInlineParseTree(root,1);
				break;
			case 3:
				//Print AST 
				printf("The Abstract Syntax Tree is traversed inorder\n");
				printInlineAstTree(AST_root,1);
				break;
			case 4:
				//Allocated Memory
				printf("Parse tree Number of nodes=%d\n",parseNodes);
				printf("Allocated Memory=%d Bytes\n",parseMem);
				printf("AST Number of nodes=%d\n",astNodes);
				printf("Allocated Memory=%d Bytes\n",astMem);
				printf("Compression percentage=%f\n",((float)(parseMem-astMem)*100)/parseMem);
				break;
			case 5:
				//populate Symbol Table and print
				mainTable=populateSymbolTable(AST_root);
				printSymbolTable(mainTable);
				break;
			case 6:
				//Print activation records and their width
				mainTable=populateSymbolTable(AST_root);
				printRecordWidth(mainTable);	
				break;
			case 7:
				//Print array variables and their info
				mainTable=populateSymbolTable(AST_root);
				printArrayVariables(mainTable);
				break;
			case 8:
				start_time = clock();
			    	root=parseInputSourceCode(argv[1]);
				AST_root=createAST(root);
				mainTable=populateSymbolTable(AST_root);
				end_time = clock();
			    
			   	total_CPU_time  =  (double) (end_time - start_time);
			    	total_CPU_time_in_seconds =   total_CPU_time / CLOCKS_PER_SEC;

			    // Print both total_CPU_time and total_CPU_time_in_seconds 
			    printf("Total CPU time = %F\n",total_CPU_time);
				printf("Total CPU time in seconds = %F\n", total_CPU_time_in_seconds);
				break;

			default:
				break;
		}
		printf("\n\n\n");
	}
}
#endif
